#!/bin/bash


################################################################################
#                                         
# |              |    |         |         
# |---.,---.,---.|---.|    ,---.|--- ,---.
# |   |,---|`---.|   ||    |---'|    `---.
# `---'`---^`---'`   '`---'`---'`---'`---'
#
#                                        
# Bashlets -- A modular extensible toolbox for Bash
#
# Copyright (c) 2014-8 Roberto Reale
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
################################################################################


#@public
function bashlets::util::datatype::phone::from_integer()
{
    # inspired from fmt-phone.sh Gist by ldante86
    # https://gist.github.com/ldante86/1e1665e8861487e52be56319f5f90e50

    local one
    local phone="$(tr -d '[:punct:]' <<< $1)"

    if [[ $phone = *[!0-9]* ]] || [ ${#phone} -lt 3 ] || [ -z "$phone" ]
    then
        return
    fi

    if [ ${#phone} -ge 11 ]
    then
        prefix="+${phone:0:${#phone}-10}-"
        phone="${phone:${#phone}-10}"
    fi

    case ${#phone} in
        6|7)
            phone="${phone:0:3}-${phone:3}" ;;
        8|9|10 )
            phone="${phone:0:3}-${phone:3:3}-${phone:6}" ;;
    esac

    echo "${prefix}${phone}"
}

# Local variables:
# mode: shell-script
# sh-basic-offset: 4
# sh-indent-comment: t
# indent-tabs-mode: nil
# End:
# ex: ts=4 sw=4 et filetype=sh
